const express = require('express');
const router = express.Router();

const glossary = [
  { id: 1, term: 'Keyboard', description: 'A keyboard is a peripheral input device used to input text, commands, and other data into a computer or electronic device. It consists of a set of keys arranged in a specific layout, such as QWERTY, and provides a means of communication between the user and the device.', reference: 'Little, J. (2019). The Complete Keyboard Guide: From Basic Typing to Advanced Shortcuts. New York, NY: ABC Publishers.' },
  { id: 2, term: 'Cloud Storage', description: 'Cloud storage refers to the storage of digital data in remote servers accessible over the internet. It allows users to store, manage, and retrieve their files and data from anywhere and on any device. Cloud storage offers scalability, data redundancy, and convenient data backup and recovery options.', reference: 'Johnson, L. (2020). Cloud Storage: A Comprehensive Guide to Storing and Managing Data in the Cloud. Boston, MA: XYZ Publishing.' },
  { id: 3, term: 'Augmented Reality', description: 'Augmented Reality (AR) is a technology that overlays digital information, such as images, videos, or 3D objects, onto the real world in real-time. It enhances the user\'s perception and interaction with the physical environment, providing a blended experience of the real and virtual worlds.', reference: 'Brown, M. (2018). Augmented Reality: Exploring the Intersection of Virtual and Real Worlds. San Francisco, CA: PQR Press.' },
  { id: 4, term: 'Machine Learning', description: 'Machine Learning is a subfield of artificial intelligence that focuses on developing algorithms and models that enable computers to learn from data and make predictions or decisions without explicit programming. It involves training and optimizing models using large datasets to uncover patterns and insights.', reference: 'Williams, R. (2019). Machine Learning in Practice: Real-world Applications and Use Cases. Seattle, WA: XYZ Publications.' },
  { id: 5, term: 'Internet of Things (IoT)', description: 'The Internet of Things (IoT) refers to the network of physical devices, vehicles, appliances, and other objects embedded with sensors, software, and connectivity capabilities that enable them to collect and exchange data. IoT allows for the integration of the physical and digital worlds, enabling various applications and services.', reference: 'Martin, S. (2020). IoT Essentials: An Introduction to the Internet of Things. Boston, MA: ABC Publishing.' },
  { id: 6, term: 'Virtual Reality', description: 'Virtual Reality (VR) is a technology that creates a simulated environment or immersive experience through the use of computer-generated visuals, sounds, and other sensory inputs. It typically involves wearing a VR headset or using specialized equipment to interact with the virtual world.', reference: 'Garcia, L. (2017). Virtual Reality: A Comprehensive Guide to Immersive Experiences. San Francisco, CA: PQR Press.' },
  { id: 7, term: 'Cryptocurrency', description: 'Cryptocurrency is a digital or virtual form of currency that uses cryptography for secure financial transactions, control the creation of additional units, and verify the transfer of assets. It operates independently of a central bank and is based on blockchain technology, ensuring transparency and decentralization.', reference: 'Johnson, M. (2021). Cryptocurrency Explained: A Beginner\'s Guide to Digital Money. New York, NY: ABC Publishers.' },
  { id: 8, term: 'Quantum Computing', description: 'Quantum Computing is an emerging field of computer science that leverages the principles of quantum mechanics to perform complex computations. It utilizes quantum bits (qubits) to represent and manipulate information, offering the potential for exponential processing power and solving problems beyond the capabilities of classical computers.', reference: 'Brown, A. (2022). Quantum Computing: Unleashing the Power of Quantum Mechanics. Seattle, WA: XYZ Publications.' },
  { id: 9, term: 'Biometric Authentication', description: 'Biometric authentication is a security measure that uses unique biological characteristics, such as fingerprints, iris patterns, or facial features, to verify and authenticate individuals\' identities. It offers a more secure and convenient alternative to traditional password-based authentication methods.', reference: 'Garcia, L. (2019). Biometrics: Enhancing Security with Unique Biological Traits. Boston, MA: ABC Publishing.' },
  { id: 10, term: 'Data Mining', description: 'Data Mining is the process of discovering patterns, relationships, and insights from large datasets. It involves using various statistical and computational techniques to extract valuable information and knowledge that can be used for decision-making, predictive modeling, and trend analysis.', reference: 'Higgins, T. (2020). Data Mining Essentials: Techniques and Applications for Knowledge Discovery. San Francisco, CA: PQR Press.' },
  { id: 11, term: 'Canary release', description: 'Canary release is a deployment strategy in which changes are been released initially. And this would reduces the risk of introducing a new version. ', reference: 'Sato, D. (2014, August 4). Canary Release. [Online]. Available: https://martinfowler.com/bliki/CanaryRelease.html [Accessed August 4, 2023]' },
  { id: 12, term: 'CI/CD', description: 'CI/CD is an integration of Continuous Integration and Continuous Delivery that would initiate certain DevOps workflows. ', reference: 'Sacolick, I. (2022). What is CI/CD? Continuous integration and continuous delivery explained. InfoWorld. [Online]. Available: https://www.infoworld.com/article/3271126/what-is-cicd-continuous-integration-and-continuous-delivery-explained.html [Accessed August 4, 2023].' },
  { id: 13, term: 'ChatOps', description: 'ChatOps would focus on communication within the DevOps teams', reference: 'Palmer, M. (2023). ChatOps Explained and Why DevOps Teams Should Care. Orange Matter. [Online]. Available: https://orangematter.solarwinds.com/2023/01/17/what-is-chatops-for-devops/ [Accessed August 4, 2023].' },
  { id: 14, term: 'Application Release Automation (ARA)', description: 'ARA is a process to package and make delays in the software release across various environments. It focuses mainly on modeling of the software and deployment of custom application software releases.', reference: 'Kumar, P. (2022). 5 DevOps Application Release Automation (ARA) Tools. H2K Infosys Blog. [Online]. Available: https://www.h2kinfosys.com/blog/5-devops-application-release-automation-ara-tools/ [Accessed August 8, 2023].' },
  { id: 15, term: 'DevSecOp', description: 'DevSecOps is about integrating security into the pipeline of continuous integration, delivery, and deployment of applications. DevSecOps incorporates security into the product to decrease software vulnerabilities.', reference: 'Das, S. (2023). DevOps Lifecycle: Different Phases in DevOps. BrowserStack Guide. [Online]. Available: https://www.browserstack.com/guide/devops-lifecycle [Accessed August 4, 2023].' },
  { id: 16, term: 'DService Level Agreement (SLA)', description: 'SLA is defined as a contractual agreement which is made between a service provider and a customer stating the expected service level and performance.', reference: 'Nauda, A. (2021). Why DevOps Teams Should Eliminate SLAs. InfoWorld. [Online]. Available: https://www.infoworld.com/article/3630104/why-devops-teams-should-eliminate-slas.html [Accessed August 4, 2023].' },
  { id: 17, term: 'CD – Continuous Delivery', description: 'Continuous delivery is a set of processes and practices followed which would automate SLDC (Software Development Life Cycle) and create a feedback loop.', reference: 'Sacolick, I. (2022). What is CI/CD? Continuous integration and continuous delivery explained. InfoWorld. [Online]. Available: https://www.infoworld.com/article/3271126/what-is-cicd-continuous-integration-and-continuous-delivery-explained.html [Accessed August 4, 2023].' },
  { id: 19, term: 'Behavior-Driven Development (BDD)', description: 'This Behavior-Driven Development - BDD is a method used in DevOps to establish standardized communication among the development teams and the project owner. ', reference: 'Goldberger, T. (2018). Behavior-driven development in DevOps. Nagarro Blog. [Online]. Available: https://www.nagarro.com/en/blog/behavior-driven-development-in-devops [Accessed August 4, 2023].' },
  { id: 20, term: 'User Acceptance testing – UAT', description: 'This user acceptance testing (UAT) helps DevOps teams to check whether a system had satisfied user demands, business requirements, etc. This testing is done every time when a new product is being developed.', reference: 'Oh, D. (2019). Automate user acceptance testing with your DevOps pipeline. Opensource.com. [Online]. Available: https://opensource.com/article/19/4/devops-pipeline-acceptance-testing [Accessed August 4, 2023].' },
];

router.get('/', function(req, res, next) {
  res.render('index', { glossary });
});

module.exports = router;
